"use strict";

const RECURSIVE_TYPE = "RECURSIVE_TYPE",
      LEFT_RECURSIVE_TYPE = "LEFT_RECURSIVE_TYPE",
      DIRECTLY_LEFT_RECURSIVE_TYPE = "DIRECTLY_LEFT_RECURSIVE_TYPE",
      INDIRECTLY_LEFT_RECURSIVE_TYPE = "INDIRECTLY_LEFT_RECURSIVE_TYPE",
      IMPLICITLY_LEFT_RECURSIVE_TYPE = "IMPLICITLY_LEFT_RECURSIVE_TYPE";

module.exports = {
  RECURSIVE_TYPE,
  LEFT_RECURSIVE_TYPE,
  DIRECTLY_LEFT_RECURSIVE_TYPE,
  INDIRECTLY_LEFT_RECURSIVE_TYPE,
  IMPLICITLY_LEFT_RECURSIVE_TYPE
};
