'use strict';

const RECURSIVE_TYPE = 'RECURSIVE',
      LEFT_RECURSIVE_TYPE = 'LEFT_RECURSIVE',
      DIRECTLY_LEFT_RECURSIVE_TYPE = 'DIRECTLY_LEFT_RECURSIVE',
      INDIRECTLY_LEFT_RECURSIVE_TYPE = 'INDIRECTLY_LEFT_RECURSIVE',
      IMPLICITLY_LEFT_RECURSIVE_TYPE = 'IMPLICITLY_LEFT_RECURSIVE';

module.exports = {
  RECURSIVE_TYPE,
  LEFT_RECURSIVE_TYPE,
  DIRECTLY_LEFT_RECURSIVE_TYPE,
  INDIRECTLY_LEFT_RECURSIVE_TYPE,
  IMPLICITLY_LEFT_RECURSIVE_TYPE
};
