"use strict";

export const RECURSIVE_TYPE = "RECURSIVE_TYPE";
export const LEFT_RECURSIVE_TYPE = "LEFT_RECURSIVE_TYPE";
export const DIRECTLY_LEFT_RECURSIVE_TYPE = "DIRECTLY_LEFT_RECURSIVE_TYPE";
export const INDIRECTLY_LEFT_RECURSIVE_TYPE = "INDIRECTLY_LEFT_RECURSIVE_TYPE";
export const IMPLICITLY_LEFT_RECURSIVE_TYPE = "IMPLICITLY_LEFT_RECURSIVE_TYPE";
